### ISSUE TITLE
spigot and fountainhead doesn't check source

### ISSUE THREAD

**Issue by asl97** [minetest-mods/pipeworks#114]
you can currently fool them both to giving water just by placing a node with `_loaded` in their name in the right place

ie: under fountainhead and behind spigot

**Comment by VanessaE** [comment]
All liquid-related problems should be checked against the new_flow_logic branch, as most likely the problem you describe has been fixed there.

**Comment by asl97** [comment]
from the code, it seem like it was fix in the `new_flow_logic` branch,  but until it get merge into master, couldn't a simple fix be release for the master branch?

or is the `new_flow_logic` branch going to be merge into master soon?

**Comment by VanessaE** [comment]
The new_flow_logic branch will be merged back to master some day - I need someone to look it over and help out with the flow/pressure deficiency.  The code logic works just fine, but the flow rate and pressure in the pipes is way too slow/low.  One person likened it to thin pipes carrying only pressurized gas. :-/

**Comment by VanessaE** [comment]
This can't be fixed in master branch, and `new_flow_logic` branch is a bust, so all "on", "loaded" and "pouring" nodes have been tweaked to force placement of the empty/off variety (where it matters).  That at least should hide this bug.  Best I can do for now.
