### ISSUE TITLE
Filter injectors let items bridge one air node

### ISSUE THREAD

**Issue by orwell96** [minetest-mods/pipeworks#123]
If items are taken out of an inventory  by a filter injector and that filter injector is NOT connected to a pipe(there is air in front of it), the items bridge one air node and then get dropped. If there is a tube one node far from the injector, the item continues travelling along that tube, as if there was a tube connection between the injector and the other tube.
see also that bunch of screenshots below.

![screenshot_20151114_214233](https://cloud.githubusercontent.com/assets/13201701/11165771/bda4f5da-8b19-11e5-9a65-fc8982a3c3a1.png)
![screenshot_20151114_214234_1](https://cloud.githubusercontent.com/assets/13201701/11165772/bda72d46-8b19-11e5-94b6-4da85cb10998.png)
![screenshot_20151114_214234_2](https://cloud.githubusercontent.com/assets/13201701/11165773/bdb20fd6-8b19-11e5-82b3-c474d8a55613.png)
the item was then found inside the chest

![screenshot_20151114_214444_1](https://cloud.githubusercontent.com/assets/13201701/11165776/bdc08700-8b19-11e5-90d9-d4fc0fa65865.png)
![screenshot_20151114_214445](https://cloud.githubusercontent.com/assets/13201701/11165778/bdce504c-8b19-11e5-85b2-c08fdb5f4034.png)
the item got dropped at the end of the second pipe

**Comment by HybridDog** [comment]
How about making the injector not work when there's nothing it can insert the item into?
