### ISSUE TITLE
spigot + wood slap + screwdriver = crash

### ISSUE THREAD

**Issue by heavygale** [minetest-mods/pipeworks#137]
A player on my server placed a pipeworks:spigot right next to moreblocks:slab_wood_1 blocks and then roated the spigot using a screwdriver. When the spigot reached a specific orientation the server crashed with the following message:

```
2016-05-16 17:15:56: ERROR[Main]: ServerError: Lua: Runtime error from mod 'pipeworks' in callback LuaABM::trigger(): Invalid position (expected table got nil).
2016-05-16 17:15:56: ERROR[Main]: stack traceback:
2016-05-16 17:15:56: ERROR[Main]:   [C]: in function 'get_node'
2016-05-16 17:15:56: ERROR[Main]:   ...minetest/bin/../mods/pipeworks/flowing_logic.lua:81: in function 'spigot_check'
2016-05-16 17:15:56: ERROR[Main]:   .../minetest/bin/../mods/pipeworks/pipes.lua:210: in function <.../minetest/bin/../mods/pipeworks/pipes.lua:209>
```

Now the server always crashes as soon as someone walks into the mapblock with the broken spigot. The only way to fix this, is by disabling the pipework mods, removing the block and reanabling pipeworks.

crime scene:
![slap](https://cloud.githubusercontent.com/assets/5744732/15294951/acb3f32e-1b8e-11e6-87e9-7dbf85801736.png)

**Comment by sofar** [comment]
https://github.com/minetest-mods/pipeworks/blob/master/flowing_logic.lua#L70

`pos` isn't checked for `nil`, but it's bizarre that the ABM would be called with this value being `nil` to begin with. Perhaps the screwdriver mucks it up.

**Comment by HybridDog** [comment]
sofar, it's line 81, the table "check" only has the keys 1,2,3 and 4, so other param2s make it crash,
what do you mean by this value being nil  to begin with?

**Comment by HybridDog** [comment]
@heavygale l fixed it:
https://github.com/HybridDog/pipeworks/commit/c7794aad60915457032ef3c1c4e8d2bda1374fba

**Comment by heavygale** [comment]
Thanks for the quick fix, no more crashs occuring!  :+1:

**Comment by sofar** [comment]
Why did you close this issue?

No changes were merged in this tree. @HybridDog needs to make a PR, and it needs to be merged before this issue can be closed.

**Comment by heavygale** [comment]
Sorry, I din't notice that I updated to HybridDog's version. Nevertheless my server doesn't crash anymore in this scenario, thanks for that.

**Comment by VanessaE** [comment]
The error doesn't correspond to the current code, and anyway this should no longer be a problem since I've added proper on-screwdriver rotation handlers.
