### ISSUE TITLE
Error loading init.lua: bad argument #2 to '?' (string expected, got function)

### ISSUE THREAD

**Issue by diogo-gomes** [minetest-mods/pipeworks#142]
After upgrade with Minetest Bower i can't load mod with Minetest.

**Version**
Minetest 0.4.14
Ubuntu 16.04

**Debug.txt**
> 2016-05-28 01:14:04: ERROR[Main]: ModError: Failed to load and run script from /home/user/.minetest/mods/pipeworks/init.lua:
> 2016-05-28 01:14:04: ERROR[Main]: bad argument #2 to '?' (string expected, got function)
> 2016-05-28 01:14:04: ERROR[Main]: stack traceback:
> 2016-05-28 01:14:04: ERROR[Main]: 	[builtin#109]: at 0x7f2254f02a00
> 2016-05-28 01:14:04: ERROR[Main]: 	[C]: in function 'open'
> 2016-05-28 01:14:04: ERROR[Main]: 	/home/user/.minetest/mods/pipeworks/init.lua:20: in main chunk

**Comment by sofar** [comment]
LuaJIT or plain Lua?

**Comment by sofar** [comment]
Please try and see if 32f331e7c4de3c5e130eff55ede475f9b212463a fixes it for you.

I can't reproduce this bug, so I'd appreciate if you can test this - it's pushed to master already.

**Comment by sofar** [comment]
@diogo-gomes please test and reply. If no reply, I'll close this as resolved.

**Comment by diogo-gomes** [comment]
Plain Lua.

[32f331e](https://github.com/minetest-mods/pipeworks/commit/32f331e7c4de3c5e130eff55ede475f9b212463a) fixes.

Thanks!
