### ISSUE TITLE
segmentation fault (core dumped) caused by pipeworks

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/pipeworks#144]
Hi there, i just restarted my public minetestserver.
Sadly, it falled into segfault loops.
After some tries i figured out that pipeworks produces it.

Even with `--trace` i dont get handy informations:
https://haste.tchncs.de/tuzayeweze.vbs

**Comment by VanessaE** [comment]
Any kind of segfault is going to be an engine issue, not a mod issue.  Please get a full backtrace with `gdb` or equivalent, and file a report against the Minetest engine.
