### ISSUE TITLE
Running pumps next to river water out to a spigot creates normal water

### ISSUE THREAD

**Issue by mtango688** [minetest-mods/pipeworks#147]
I believe the idea behind river water is that it provides a finite source of water, but by simply connecting a pump next to river water to a spigot, that will create the normal default water, which is inifinite.

**Comment by VanessaE** [comment]
This can't be fixed until someone tidies up and rebases the "[new_flow_logic](https://github.com/minetest-mods/pipeworks/commits/new_flow_logic)" branch.  Although that branch can't be directly used with anything besides regular water, I did make the code with multiple fluids in mind.

**Comment by mtango688** [comment]
So, we can look forward to a PR in the near future?

As for water, it appears that using group:water is the way to go for checking, except you then have to check for liquid_renewable to exclude finite water from being duplicated.

**Comment by VanessaE** [comment]
I couldn't say.  The code is there and it works fine, but it needs some tuning to get the flow rates/pressure right for water (right now it behaves more like air I guess).

**Comment by mtango688** [comment]
Funny. I was just thinking that water in Minetest behaves more like a thick goo than like real water. I guess every side of this equation has a ways to go...

**Comment by VanessaE** [comment]
The `new_flow_logic` branch was a bust, no one ever stepped up to work on it, and the current code can't handle pouring actual river wter, so I'm closing this as "can't fix".
