### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by raymoo** [minetest-mods/pipeworks#148]
Document the public API

**Comment by VanessaE** [comment]
Does pipeworks even HAVE a public API as such?

**Comment by raymoo** [comment]
What about the things in the tube definitions like `can_insert` and `insert_object` that are even used in Technic?

**Comment by VanessaE** [comment]
I guess that's a yes. :)

**Comment by DS-Minetest** [comment]
Should the wiki be used to document the API or should a file (like `api.md`) be added?

**Comment by VanessaE** [comment]
imho that's something that could go into the wiki.

**Comment by DS-Minetest** [comment]
I began listing all functions and some other things: https://github.com/minetest-mods/pipeworks/wiki/API

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues
