### ISSUE TITLE
Digilines teleport tubes

### ISSUE THREAD

**Issue by raymoo** [minetest-mods/pipeworks#151]
Make teleport tubes take digilines messages to set the channel, and also make them emit messages when receiving an item.

An example use case would be a remote banking system, where you can send a book containing formatted commands to withdraw money. The "server" would then send cash to the "return address" (a channel) specified in a book.

**Comment by DS-Minetest** [comment]
that would be a bit cheaty

**Comment by raymoo** [comment]
Cheaty how?

**Comment by DS-Minetest** [comment]
You would only need one teleport tube.

**Comment by raymoo** [comment]
Alright, that makes sense.
