### ISSUE TITLE
Make Deployers Work With Items

### ISSUE THREAD

**Issue by benrob0329** [minetest-mods/pipeworks#153]
For eg. If an item is in the deployer, have the item tossed out some distance away.

Other eg could include arrows (https://forum.minetest.net/viewtopic.php?f=11&t=14384), giving the option to place/toss or shoot/launch, Mobs_Redo spawners, and perhaps equip armor? (That last one might be more trouble than its worth).

The way it could be done is by checking to see if the item to be deployed matches a special behavior, then checking for a launch/place boolean. If it doesn't match a special behavior, then simply do the default based on current settings.

**Comment by raymoo** [comment]
What about using a callback from the item definition if defined?

**Comment by VanessaE** [comment]
Use a dispenser for this purpose.
