### ISSUE TITLE
Pollution of global namespace and core-provided tables.

### ISSUE THREAD

**Issue by beyondlimits** [minetest-mods/pipeworks#154]
I have found that pipeworks code pollutes global namespace and messes up with core-provided tables:
```
pipeworks
```
Okay, the above is fine. This is a mod namespace. However it goes beyond that:
```
directions
luaentity
fs_helpers
minetest.facedir_to_right_dir
minetest.facedir_to_top_dir
minetest.load_position
string.startswith
table.contains
table.extend
table.recursive_replace
vector.cross
vector.dot
```

Core-provided tables should be modified with great care. Minetest through its development may have functions defined with its own namespace, who knows it won't be called `facedir_to_right_dir`, `facedir_to_top_dir` or `load_position`. One day Minetest may use higher version of Lua which might come with `table.contains` etc. Your mod doesn't even check if entries within the tables already exist.

**Comment by sofar** [comment]
Ack, this is not good.

**Comment by ForbiddenJ** [comment]
Yep, not good. I use print functions to print a list of functions contained within tables. However, this will really cause me issues.

I make my own functions that relate to tables, but they are named like table_indexof, table_reverse and so on because I prefer not messing with system tables.

**Comment by kaeza** [comment]
#167 fixed this.

Thank you for reporting!
