### ISSUE TITLE
Sorting tube priorities

### ISSUE THREAD

**Issue by webD97** [minetest-mods/pipeworks#164]
> it seems that the lowest-priority "just bounce backwards if nowhere to go" is overriding the priority of a sorting tube's unsorted outputs

**Comment by cheapie** [comment]
Haven't they always done this? I'm pretty sure it was supposed to be by design. Turn the input off if you don't want stuff going out that way.

**Comment by VanessaE** [comment]
That may be the case, and if that's the desired behavior, that's fine, but then the Wiki needs updated accordingly.

**Comment by cheapie** [comment]
It already says "If there are no items in the row, all items are allowed", with nothing excluding the way it came.

**Comment by VanessaE** [comment]
Good point, though logic would suggest that the way an item came should be the last thing the tube tries. :stuck_out_tongue:

**Comment by VanessaE** [comment]
I've updated the Wiki to clarify.
