### ISSUE TITLE
[TODO] autocrafter: add "alternative" button to swap output because of overlapping recipes

### ISSUE THREAD

**Issue by DS-Minetest** [minetest-mods/pipeworks#172]
Title says mostly all.
There are already mods to fix overlapping recipes (eg. easy crafting table) for manual crafting but it is also needed for automatic stuff.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues
