### ISSUE TITLE
My chests have turned pink!

### ISSUE THREAD

**Issue by enkidu-smith** [minetest-mods/pipeworks#175]
It appears that [a recent change in minetest-game](https://github.com/minetest/minetest_game/issues/1725), specifically the chests part of it, may have caused the deletion of some of the images for the default chest. 

Pipeworks refers to these images, so I think it might be the source of the errors I mentioned in the issue that I referred to above. For example, at around line 37 in compat-chests.lua this code refers to the missing images
```
minetest.override_item("default:chest", {
	tiles = {
		"default_chest_top.png"..tube_entry,
		"default_chest_top.png"..tube_entry,
		"default_chest_side.png"..tube_entry,
		"default_chest_side.png"..tube_entry,
		"default_chest_side.png"..tube_entry,
		"default_chest_front.png"
	},
```
I'm pretty sure that this issue is why my default chests have all turned pink! I don't know whether this should be fixed in this mod or the game, so this is just to acquaint you of the (possible) issue.

**Comment by DS-Minetest** [comment]
The whole chest overriding code has to be changed, not only the part with the textures.

**Comment by sofar** [comment]
The old textures were put back for use in non-mtg mods, so this is fixed.

**Comment by mtango688** [comment]
Actually, this is still a problem.

**Comment by enkidu-smith** [comment]
I don't have the original textures back. My chests have a wooden look to them, but it seems that the image is not correct. I have the latest gits of minetest (441740e), and minetest_game (c7d558c).
![screenshot_20170511_211355](https://cloud.githubusercontent.com/assets/6015685/25941823/e816ca2e-368e-11e7-87d9-364ee413c002.png)

**Comment by DS-Minetest** [comment]
@enkidu-smith The reason for this is that pipeworks overrides the chest and so gives it the wrong texture. We should wait with changes in pipeworks until there's nothing changed anymore in minetest_game about the chests.

**Comment by enkidu-smith** [comment]
Thanks.

**Comment by DS-Minetest** [comment]
This should be fixed now.

**Comment by enkidu-smith** [comment]
Yep, it has been fixed for me. The old appearance is back. I'm not sure of the relationships between minetest, minetest_game and the pipeworks mod itself, but when I updated all three, the issue was fixed.

**Comment by enkidu-smith** [comment]
Closed as fixed.
