### ISSUE TITLE
Make filters work like autocrafters - use a template copy of the item being placed in the filter

### ISSUE THREAD

**Issue by JDCodeIt** [minetest-mods/pipeworks#176]
It seems strange to have filters store the inventory of the items being filtered. It might be better if they worked more like autocrafters and used a template copy of the item/quantity.

A small change to the code can make this possible:
`		allow_metadata_inventory_put = function(pos, listname, index, stack, player)
			if not pipeworks.may_configure(pos, player) then return 0 end
			local inv = minetest.get_meta(pos):get_inventory()
			inv:set_stack("main", index, stack)
			return 0
		end,
		allow_metadata_inventory_take = function(pos, listname, index, stack, player)
			if not pipeworks.may_configure(pos, player) then return 0 end
			local inv = minetest.get_meta(pos):get_inventory()
			inv:set_stack("main", index, ItemStack(""))
			return 0
		end,
`

**Comment by DS-Minetest** [comment]
Sorting tubes also use it.

The problem is that items would be deleted, that are from the old filters.
Hm, could there be an additional inventory for the old items that's contend is dropped after dig?

**Comment by benrob0329** [comment]
Perhaps just drop the extra items above it.
