### ISSUE TITLE
Undeclared global variable "nodecolor"

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/pipeworks#178]
I am getting the following warning when running my server:

> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "nodecolor" accessed at ...est/games/antum-testing/mods/pipeworks/routing_tubes.lua:15
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "nodecolor" accessed at ...est/games/antum-testing/mods/pipeworks/routing_tubes.lua:16
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "nodecolor" accessed at ...est/games/antum-testing/mods/pipeworks/routing_tubes.lua:17
> 2017-05-13 13:14:54: WARNING[Main]: Undeclared global variable "nodecolor" accessed at ...est/games/antum-testing/mods/pipeworks/routing_tubes.lua:18

The first occurrence of ***nodecolor*** is in [line 15 of *routing_tables.lua*][L15]. *nodecolor* is declared locally in [line 69][L69], but it is not within scope of the other calls to it. Turning off ***pipeworks_enable_priority_tube*** does not remove the warning message.

I am using [***pipeworks*** build d822279][build.pipeworks] with [***Minetest*** server build 0d4d35a][build.minetest].

[build.pipeworks]: https://github.com/minetest-mods/pipeworks/tree/d82227942d3a9e4c68582224327cab13e6556753
[build.minetest]: https://github.com/minetest/minetest/tree/0d4d35a
[L15]: https://github.com/minetest-mods/pipeworks/blob/d82227942d3a9e4c68582224327cab13e6556753/routing_tubes.lua#L15
[L69]: https://github.com/minetest-mods/pipeworks/blob/d82227942d3a9e4c68582224327cab13e6556753/routing_tubes.lua#L69

**Comment by DS-Minetest** [comment]
I also recognized that, it should be easy to fix.

**Comment by AntumDeluge** [comment]
Fixed by #185.

**Comment by DS-Minetest** [comment]
@AntumDeluge You can close this by yourself.

**Comment by AntumDeluge** [comment]
@DS-Minetest Thank you. I was on a mobile device last night using [OctoDroid](https://github.com/slapperwan/gh4a), & it wasn't letting me close it.
