### ISSUE TITLE
Upgrading pipeworks destroyed the contents of locked wooden chest

### ISSUE THREAD

**Issue by AntumDeluge** [minetest-mods/pipeworks#180]
Within the last week or two I upgraded pipeworks to build d822279. I didn't realize it until some of the players on my server started complaining that the items from their locked wooden chests were missing. Luckily I had run backups of the server.

I am not sure which build I was using previously, but it didn't happen until I upgraded & a button labeled "Allow splitting incoming stacks from tubes" appeared in the opened chests.

A strange artifact is that after the upgrade, the first time a chest is opened, the upper half (chest contents) is blank without any item slots. The second time it is opened, again no item slots, but the "Allow splitting" button appears. The third time, the slots appear, but they are all empty. I suspect this artifact/bug may be the cause of the items being deleted.

The only chests that appear to be affected so far are locked wooden chests.

Attached are screenshots of a server running without pipeworks installed, followed by three more screenshots of the artifact that I described above.

*Without pipeworks installed:*
![Screenshot 1][sshot1]

*Installed pipeworks d822279:*
![Screenshot 2][sshot2]
![Screenshot 3][sshot3]
![Screenshot 4][sshot4]

Something else that I noticed, though I don't know if it is relevant, is that in the last screenshot, the background is not shaded & the item slots are lighter in color. I should also mention that the [technic][] mod is installed, but depends on pipeworks. So it was not active when the first screenshot was taken.

[technic]: https://github.com/minetest-mods/technic
[sshot1]: https://cloud.githubusercontent.com/assets/3631473/26038795/30628dee-38c5-11e7-9b76-c327b88c04a8.png
[sshot2]: https://cloud.githubusercontent.com/assets/3631473/26038810/5bd1d5ca-38c5-11e7-8b62-708a8d2f59dd.png
[sshot3]: https://cloud.githubusercontent.com/assets/3631473/26038812/6235dbaa-38c5-11e7-8dd7-fb4554bda4ae.png
[sshot4]: https://cloud.githubusercontent.com/assets/3631473/26038814/7090683c-38c5-11e7-8fef-80ea2ccbf6b4.png

**Comment by AntumDeluge** [comment]
Downgrading `pipeworks` to Git commit a3d2e69 fixes the problem for me.

**Comment by ForbiddenJ** [comment]
I don't know what to tell you. I really don't like how this mod modifies formspecs of chests merely to put in a switch I'll probably never use. I'd rather that be a special "splitting" tube.

**Comment by DS-Minetest** [comment]
Btw there's a setting which disables the modifying of chests.

**Comment by VanessaE** [comment]
I had this happen without pipeworks as well.  It was a bug in minetest_game that has since been fixed, as far as I am aware.

**Comment by AntumDeluge** [comment]
Okay, so if I understand correctly @VanessaE , the bug was in *minetest_game* & affected *pipeworks*. So, with the release of Minetest 0.4.16, I should be able to update to the latest stable releases of both without seeing the issue?

**Comment by VanessaE** [comment]
It should, yes.  I don't seem to have any such problem with chests in current pipeworks+mt_game+minetest 0.4.16

**Comment by AntumDeluge** [comment]
Thank you. I will try it.
