### ISSUE TITLE
Usage of semantic versioning and github tags

### ISSUE THREAD

**Issue by diogo-gomes** [minetest-mods/pipeworks#182]
I propose the usage of [semantic versioning](http://semver.org/) and GitHub tags.

The actual master branch of pipeworks is incompatible with stable version of Minetest (0.4.15) and if someone want a compatible version of mod is inconvenient to search in commit history.

I propose GitHub tags, it's more easy to manage with Bower and to download.

### **Important**
**My suggestion isn't create version tags like Minetest but create own version tags.**
Example: 1.0.0, etc

**Comment by VanessaE** [comment]
This is already planned, and this particular issue doesn't really apply anymore since 0.4.16 came out last month.  I've added a tag for 0.4.16.
