### ISSUE TITLE
error when loading new game

### ISSUE THREAD

**Issue by YruamaLairba** [minetest-mods/pipeworks#183]
i get  the error "default_settings.lua: 33 attempt to index filed 'setting' (a nil value)"
i'm using minetest 0.4.15 on windows

**Comment by YruamaLairba** [comment]
i think i have found the problem, i seen many "minetest.settings:get_bool()" call but that is not part of the api, maybe you should want to use "minetest.setting_getbool" instead

**Comment by DS-Minetest** [comment]
@YruamaLairba Could you wait one day for 0.4.16 release?

**Comment by VanessaE** [comment]
I already wrote in the forum that you need a development build of Minetest to use this (or as @DS-Minetest said, wait for 0.4.16-release, tomorrow).

**Comment by DS-Minetest** [comment]
Perhaps it would be good to make releases or tags of the current pipeworks every time when minetest is released.

**Comment by VanessaE** [comment]
There already is a 0.4.15 tag.

**Comment by YruamaLairba** [comment]
so, in fact, i just download a wrong version ?

**Comment by VanessaE** [comment]
You did, but as 0.4.15 is obsolete now (actually, has been for months), I would recommend waiting until tomorrow, upgrading your Minetest build to 0.4.16, and then trying current git of Pipeworks again.

I'll omit any future tags until something goes in that would break Pipeworks for 0.4.16 users.

**Comment by DS-Minetest** [comment]
>There already is a 0.4.15 tag.

I just can't find it. >_< https://github.com/minetest-mods/pipeworks/tags

**Comment by VanessaE** [comment]
Strange.  I could swear I tagged it.  Oh well.  Shortly after 0.4.16 goes out, I'll tag it for that version (some minor fixes to chests will be needed first).
