### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by mase76** [minetest-mods/pipeworks#189]
Hi!
I already posted in the forum topic, that I get this error with the minetest-server 0.4.16 and pipeworks git
on debian stretch:
`ERROR[Main]: ModError: Failed to load and run script from /usr/share/games/minetest/games/myworld/mods/pipeworks/init.lua:
ERROR[Main]: /usr/share/games/minetest/builtin/common/misc_helpers.lua:590: table index is nil
ERROR[Main]: stack traceback:
ERROR[Main]:    /usr/share/games/minetest/builtin/common/misc_helpers.lua:590: in function 'copy'
ERROR[Main]:    ...test/games/myworld/mods/pipeworks/compat-chests.lua:93: in main chunk
ERROR[Main]:    [C]: in function 'dofile'
ERROR[Main]:    ...ames/minetest/games/myworld/mods/pipeworks/init.lua:117: in main chunk`

**Comment by mase76** [comment]
This error does not occur when creating a game in the client.
Only the dedicated server is affected.

**Comment by DS-Minetest** [comment]
Hm, `minetest.registered_items["default:chest_open"]` is nil.
@mase76 Do you also use minetest_game 0.4.16 on your server?

**Comment by mase76** [comment]
Yes, client and server are both 0.4.16. I built the debian sid sourcepackage for stretch.

**Comment by DS-Minetest** [comment]
I mean, do you use another subgame?

**Comment by mase76** [comment]
The subgame is the git checkout of the minetest game.

**Comment by mase76** [comment]
Oh damned! My minetest game checkout wasn't constistent.
Did a new checkout. It works now.

**Comment by fgrosswig** [comment]
did not get this hint. what you mean by "wasnt checkout" ?? currently have the same issue above.
