### ISSUE TITLE
Server crash on right click

### ISSUE THREAD

**Issue by fireglow** [minetest-mods/pipeworks#207]
Server crash on right click when chest lid is obstructed with unknown node:

```
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback item_OnPlace(): /srv/minetest/world/worldmods/pipeworks/compat-chests.
lua:47: attempt to index local 'def' (a nil value)                                       
ERROR[Main]: stack traceback:                                       
ERROR[Main]:       /srv/minetest/world/worldmods/pipeworks/compat-chests.lua:47: in function 'chest_lid_obstructed'
ERROR[Main]:       /srv/minetest/world/worldmods/pipeworks/compat-chests.lua:119: in function 'on_rightclick'
ERROR[Main]:       /srv/minetest/world/worldmods/torches/init.lua:40: in function </srv/minetest/world/worldmods/torches/init.lua:30>
```

**Comment by thetaepsilon-gamedev** [comment]
I'm able to reproduce this quite easily on my test world by removing a mod to cause unknown nodes.
It's quite evident why it would blow up like this - the mentioned use of def in compat-chests.lua would return nil for an unknown node.
However, I'm inclined to WONTFIX this on account of there are probably a lot of similar cases in the code  where if a node name comes from minetest.get_node(), it's assumed to be valid and therefore minetest.registered_nodes[node.name] is assumed to be present.
If I were to fix this one case it would seem odd considering all those other cases, and in general I would consider any kind of interaction with unknown nodes as undefinied behaviour - that is, all guarantees are off and expect explosions, you should remove these nodes from your world where possible.

That said, if this kind of problem (that is, nil ref crashes from unknown nodes) were to occur in an ABM say and it prevents the server from running long enough to correct the issue, then I would be willing to consider those crashes on a case-by-case basis.

**Comment by VanessaE** [comment]
My norm here is to fix the crash, actually.  Unknown nodes happen all the time in Minetest worlds, especially on servers, and users have a habit of deliberately causing crashes just to piss off others, especially if no one else knows there the unknown node is.

In most mods in Minetest, Pipeworks included, one should basically treat unknown nodes as if they're cobble or dirt, or something else completely inert.
