### ISSUE TITLE
Chest lid obstruction function can't be overridden

### ISSUE THREAD

**Issue by HybridDog** [minetest-mods/pipeworks#210]
For my connected_chests mod I need to override the chest lid obstruction function to avoid replacing the big chest with a small opened one when right clicking it. With pipeworks installed it doesn't work because it uses a local copy-paste copy of the function.
https://github.com/minetest-mods/pipeworks/blob/master/compat-chests.lua#L43

**Comment by VanessaE** [comment]
Can't fix this, sorry
