### ISSUE TITLE
Injector crash privileged user pulling from locked chest

### ISSUE THREAD

**Issue by JDCodeIt** [minetest-mods/pipeworks#214]
Hi, I found an issue in the function grabAndFire in file filter-injector.lua, where a table (fakePlayer) is being passed instead of a user name. This eventually causes a crash in the builtin function that checks for protection, which is expecting only a player name.

fakePlayer is defined as a table
```` Lua
	local fakePlayer = {
		get_player_name = delay(owner),
		is_fake_player = ":pipeworks",
		get_wielded_item = delay(ItemStack(nil))
	} -- TODO: use a mechanism as the wielder one
````
File: filter-injector.lua
Function:  grabAndFire
Line: 154

Original line
```` Lua 
fromdef.on_metadata_inventory_take(frompos, frominvname, spos, item, fakePlayer)
````
Fixed line
```` Lua
doRemove = fromdef.allow_metadata_inventory_take(frompos, frominvname,spos, stack, fakePlayer:get_player_name())
````

**Comment by electrodude** [comment]
Why don't you create a pull request for this?

**Comment by JDCodeIt** [comment]
Actually, I looked at the call stack again and is the bug really in mods/default in minetest_game?
According to the Dev Wiki - check_player_privs() takes a name, not a player object. So can_interact_with_node() should have passed a name.
```` Lua
filter-injector.lua [154] doRemove = allow_metadata_inventory_take(frompos, frominvname,spos, stack, fakePlayer)

minetest_game/mods/default/nodes.lua : function default.chest.register_chest(name, d)
...
		def.allow_metadata_inventory_take = function(pos, listname, index, stack, player)
if not default.can_interact_with_node(player, pos) then
...

minetest_game/mods/default/functions.lua: function default.can_interact_with_node(player, pos)
	if player then
		if minetest.check_player_privs(player, "protection_bypass") then
return true

minetest.check_player_privs("name", {privs})
 Parameters
1: Player name
2: List of boolean permissions

**Comment by JDCodeIt** [comment]
...Then you look at the API document and see that check_player_privs() is supposed to support a player object or name as a string.  The implementation of check_player_privs() calls core.is_player() - but this fails with the "fakePlayer" being passed from pipeworks. I will put in a pull request to fix this.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues
