### ISSUE TITLE
Valves do not render correctly when screwdrivered (see image)

### ISSUE THREAD

**Issue by MFernflower** [minetest-mods/pipeworks#64]
![rendererror](https://cloud.githubusercontent.com/assets/3164942/2923626/21c38de6-d71c-11e3-8c09-9b401471cc8b.png)

**Comment by VanessaE** [comment]
88ad79163dab74d247d6e70aba5ec7b1f7d4a3b8, e5ee0dee907ca083846513ddc2eede4ac5c1da6b
