### ISSUE TITLE
Suggestion:  Use animations instead of moving entities.

### ISSUE THREAD

**Issue by Ecu** [minetest-mods/pipeworks#70]
I mentioned this in IRC and V suggested I post it here, a solution to the glitchy entity positions client-side could potentially be to actually use dummy models with animations that move the item a certain distance over a set time frame instead.  

You could then just spawn that as an entity with the item attached to move it smoothly each step instead.

**Comment by HybridDog** [comment]
>My initial estimate is that it 'should' be better on performance due to not actually having to change entity information constantly. Similarly on a server, not needing to update that should mean less packet spam. 

as far as l know the velocity and position is sent only when it changes

**Comment by sofar** [comment]
Particles would be far better performing - they can be skinned using textures from the items as they flow through the pipe, and have no entities or map data present. Instead, the actual items could be cached and moved around by e.g. nodetimers storing the item and placing the appropriate particle...

**Comment by Ecu** [comment]
> Particles would be far better performing - they can be skinned using textures from the items as they flow through the pipe, and have no entities or map data present. Instead, the actual items could be cached and moved around by e.g. nodetimers storing the item and placing the appropriate particle...
Wow.  Haven't even looked at MT in quite awhile, but got an email notification of this reply.  Curiously, does MT now have 3D particles?  I ask because you probably don't want to use sprites for blocks that utilize 3D models for their representation instead.  Performance-wise though it definitely sounds like a solid solution.

**Comment by sofar** [comment]
It solves the disappearing item problem (pipes could cache items in nodemetadata), but yes it would look less impressive than nice cubes.

**Comment by Ekdohibs** [comment]
@sofar Well, the disappearing item problem is a purely visual one -- items are entirely handled by Lua but sometimes the entity disappears, even though the item is still there in Lua.
