### ISSUE TITLE
crash with many objects due to luajit limitations on table size

### ISSUE THREAD

**Issue by iqualfragile** [minetest-mods/pipeworks#75]
```
09:26:51: ERROR[ServerThread]: core.deserialize(): /home/minetest/minetest/bin/../builtin/common/serialize.lua:181: [string "return { { ["_velocity"] = { ["y"] = 0, ["x"]..."]:1: main function has more than 65536 constants
09:26:51: ACTION[ServerThread]: Announcing to servers.minetest.net
09:26:51: ACTION[main]:         .__               __                   __
09:26:51: ACTION[main]:   _____ |__| ____   _____/  |_  ____   _______/  |_
09:26:51: ACTION[main]:  /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
09:26:51: ACTION[main]: |  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |
09:26:51: ACTION[main]: |__|_|  /__|___|  /\___  >__|  \___  >____  > |__|
09:26:51: ACTION[main]:       \/        \/     \/          \/     \/
09:26:51: ACTION[main]: World at [/home/minetest/minetest/bin/../worlds/newworld]
09:26:51: ACTION[main]: Server for gameid="minetest" listening on :::30000.
terminate called after throwing an instance of 'LuaError'
  what():  /home/minetest/minetest/bin/../mods/pipeworks/luaentity.lua:32: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        /home/minetest/minetest/bin/../mods/pipeworks/luaentity.lua:32: in function </home/minetest/minetest/bin/../mods/pipeworks/luaentity.lua:31>
        /home/minetest/minetest/bin/../builtin/game/register.lua:348: in function </home/minetest/minetest/bin/../builtin/game/register.lua:336>
```

**Comment by sofar** [comment]
@Ekdohibs might we close this?

**Comment by Ekdohibs** [comment]
@sofar Well, I would say we need a proper fix for it: either hand-serializing the data, which might make it a bit more space-efficient, or finding another way. Imho, hand-serializing would be better, because it would be faster and take a lot less space, but that may be a bit painful to code.

**Comment by iqualfragile** [comment]
@sofar no this can not be closed yet, as it is not yet fixed.
it is not an engine bug either, its a limitation of luajit.
but luajit is necessary to run pipeworks, at least if you have more then 3 pipes.

**Comment by HybridDog** [comment]
you could rename the title of the issue (e.g. to "crash due to luajit problem with deserialization")

After serializing data, you could use minetest.compress, so adding spaces etc. doesn't mean direct proportional increased space size for table size

**Comment by iqualfragile** [comment]
yes, but compression would not help with the problem of having too many elements in the table.
maybe an option would be to split it up? one table each like 16 blocks?

**Comment by HybridDog** [comment]
you could also try to reduce the contents of the table, e.g. omit coordinates of vectors if they're 0

**Comment by HybridDog** [comment]
l recently edited the paintings mod and the big canvas (64x64) didn't longer cause a crash if you drew too much,
@iqualfragile, does this crash still happen?

**Comment by iqualfragile** [comment]
@HybridDog im not really actively running a server anymore, so i can't tell

**Comment by VanessaE** [comment]
I haven't seen any kind of memory limitations since this bug was filed, and LuaJIT has GC64 now.  Closing.
