### ISSUE TITLE
Idea: Give filters (of injectors & sorting tubes) ability to take tool wear into account

### ISSUE THREAD

**Issue by thatgraemeguy** [minetest-mods/pipeworks#77]
I have this idea but I'm not sure if its possible, so hopefully this is a good way to get some input.

While building an obsidian generator using mesecon bits and technic's lava cans I realised that because the lava cans are implemented as tools, they are all considered identical from an injector's filters' point of view, since they are all the same node, with the level of fullness stored in the wear level of the tool.

I thought it may be useful for filters to be able to take the wear level into account, so that empty cans could be filtered and removed from the system, which I currently have to do manually every now and then.

**Comment by electrodude** [comment]
Digiline filter-injectors can do this.  Send one a message `{name="mod_name:tool_name", count=1, wear={100,1000}}`, and it should only take items with wear in the range `[100, 1000)`.  I wrote that code, but I don't remember if I ever tested it properly.

**Comment by VanessaE** [comment]
This project has been moved to Gitlab.  Please copy/paste/re-open your issue there.  https://gitlab.com/VanessaE/pipeworks/issues
